var a= 3;
var b= 5;
var c = a-b;
var d  = a*b;
var e= a/b;
var f = a**b;
document.write("Subtraction of 3 and 5 is "+c+"<br>");
document.write("Multiplication of 3 and 5 is "+d+"<br>");
document.write("Division of 3 and 5 is "+e+"<br>");
document.write("Modulus of 3 and 5 is "+f+"<br>");